#!/bin/bash

HEADER_FILE="include/build_attributes.h"
TMP_FILE="${HEADER_FILE}.tmp"

# Get short hash and convert to uppercase
GIT_COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null | tr '[:lower:]' '[:upper:]')
BUILD_TIMESTAMP=$(date +%s)

cat <<EOF > "$TMP_FILE"
#ifndef __BUILD_ATTRIBUTES_H__
#define __BUILD_ATTRIBUTES_H__
/*
 * This is an auto generated file by build_attributes.sh
 * Do not edit this file manually
 */

#define GIT_COMMIT_HASH "${GIT_COMMIT_HASH}"
#define BUILD_TIMESTAMP "${BUILD_TIMESTAMP}"
#endif
EOF

# Only update header if contents actually changed
if ! cmp -s "$TMP_FILE" "$HEADER_FILE"; then
    echo "Updating $HEADER_FILE"
    mv "$TMP_FILE" "$HEADER_FILE"
else
    rm "$TMP_FILE"
fi
